# Hyper parameter tunning using GridSearchCV

In [2]:
import pandas as pd

In [3]:
from sklearn import datasets
iris=datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [5]:
df["flower_name"]=iris.target
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower_name
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [6]:
df["flower_name"]=iris.target_names[iris.target]
df
### 0,1,2 ar jaigai flower name bosaisi setosa,,versicolur,verginica

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower_name
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [7]:
x=df.drop("flower_name",axis=1)
x

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [8]:
y=df["flower_name"]
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: flower_name, Length: 150, dtype: object

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=6)

In [10]:
x_train

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
45,4.8,3.0,1.4,0.3
59,5.2,2.7,3.9,1.4
16,5.4,3.9,1.3,0.4
13,4.3,3.0,1.1,0.1
133,6.3,2.8,5.1,1.5
...,...,...,...,...
148,6.2,3.4,5.4,2.3
79,5.7,2.6,3.5,1.0
109,7.2,3.6,6.1,2.5
106,4.9,2.5,4.5,1.7


In [11]:
x_test

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
4,5.0,3.6,1.4,0.2
116,6.5,3.0,5.5,1.8
2,4.7,3.2,1.3,0.2
23,5.1,3.3,1.7,0.5
123,6.3,2.7,4.9,1.8
96,5.7,2.9,4.2,1.3
134,6.1,2.6,5.6,1.4
39,5.1,3.4,1.5,0.2
137,6.4,3.1,5.5,1.8
53,5.5,2.3,4.0,1.3


In [12]:
x_test.shape

(30, 4)

In [13]:
y_train

45         setosa
59     versicolor
16         setosa
13         setosa
133     virginica
          ...    
148     virginica
79     versicolor
109     virginica
106     virginica
138     virginica
Name: flower_name, Length: 120, dtype: object

In [14]:
y_test

4          setosa
116     virginica
2          setosa
23         setosa
123     virginica
96     versicolor
134     virginica
39         setosa
137     virginica
53     versicolor
127     virginica
81     versicolor
115     virginica
135     virginica
74     versicolor
119     virginica
105     virginica
51     versicolor
92     versicolor
32         setosa
37         setosa
120     virginica
44         setosa
0          setosa
55     versicolor
72     versicolor
87     versicolor
102     virginica
30         setosa
93     versicolor
Name: flower_name, dtype: object

In [15]:
y_test.shape

(30,)

In [16]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [17]:
model.score(x_test,y_test)

1.0

In [18]:
###akn amra nise grid search cv library deye dakhbo svc() ar modde kon perameter best hoi,,
###pore aisa seita debo

# use GridSearchCV

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
arman=GridSearchCV(SVC(gamma="auto"),{
    "C":[1,10,20,30],
    "kernel":["rbf","linear","poly"]
}, cv=5)
arman.fit(x,y)
arman.cv_results_

{'mean_fit_time': array([0.00385294, 0.00342855, 0.00480142, 0.00327306, 0.00326405,
        0.00794835, 0.0046175 , 0.00315471, 0.01353879, 0.00345278,
        0.00379124, 0.01193733]),
 'std_fit_time': array([0.0008275 , 0.00037259, 0.00148875, 0.0001822 , 0.00033207,
        0.00355217, 0.00214906, 0.00023344, 0.00687899, 0.00020864,
        0.0004332 , 0.00713284]),
 'mean_score_time': array([0.00296206, 0.00292587, 0.00263844, 0.00252719, 0.00245471,
        0.00328593, 0.00247068, 0.00246987, 0.00415277, 0.00286322,
        0.00247865, 0.00277162]),
 'std_score_time': array([0.00041229, 0.00077326, 0.00025296, 0.00015593, 0.00012763,
        0.00060985, 0.00012654, 0.00011089, 0.00166088, 0.00045376,
        0.00020491, 0.00038249]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20, 30, 30, 30],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_kernel': mas

In [21]:
df=pd.DataFrame(arman.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003853,0.000827,0.002962,0.000412,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003429,0.000373,0.002926,0.000773,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004801,0.001489,0.002638,0.000253,1,poly,"{'C': 1, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
3,0.003273,0.000182,0.002527,0.000156,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.003264,0.000332,0.002455,0.000128,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
5,0.007948,0.003552,0.003286,0.000610,10,poly,"{'C': 10, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.004618,0.002149,0.002471,0.000127,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
7,0.003155,0.000233,0.002470,0.000111,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
8,0.013539,0.006879,0.004153,0.001661,20,poly,"{'C': 20, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
9,0.003453,0.000209,0.002863,0.000454,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,9


In [22]:
arman.best_params_

{'C': 1, 'kernel': 'rbf'}

In [23]:
arman.best_score_

np.float64(0.9800000000000001)

# approch 2 : use k fold cross validation

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
sv1=cross_val_score(SVC(kernel="rbf",C=1,gamma="auto"),x,y,cv=5)
sv1

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [26]:
sv1.mean()

np.float64(0.9800000000000001)

In [27]:
sv2=cross_val_score(SVC(kernel="linear",C=20,gamma="auto"),x,y,cv=5)
sv2
###akane amra nij theke perameter deye daksi

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [28]:
sv2.mean()
###nijer issa moto kernel perameter dele accuracy kome jai

np.float64(0.9666666666666666)

In [29]:
###akn amra bivinno model deye dakhbo


In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
sv3=cross_val_score(DecisionTreeClassifier(),x,y,cv=5)
sv3

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [32]:
sv3.mean()
###decision tree te accuracy aro basi kome jai

np.float64(0.9666666666666668)

In [33]:
from sklearn.naive_bayes import GaussianNB

In [34]:
sv4=cross_val_score(GaussianNB(),x,y,cv=5)
sv4

array([0.93333333, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [35]:
sv4.mean()
###naive bayes a o accuracy kome jai

np.float64(0.9533333333333334)

In [36]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
 sv5=cross_val_score(KNeighborsClassifier(n_neighbors=3),x,y,cv=5)
sv5

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [38]:
sv5.mean()

np.float64(0.9666666666666668)

# akn amra amader main cancer data deye grid seacrch test korbo

In [39]:
import os 
os.chdir("C:/Users/arman/ostad_code")

In [40]:
df=pd.read_csv("Breast_Cancer_Diagnostic.csv")
df

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,M
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,M
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,M
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,M
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,M
...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,M
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,M
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,M
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,M


In [41]:
x=df.drop("diagnosis",axis=1)
y=df["diagnosis"]

In [42]:
x

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883
...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016


In [43]:
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [44]:
from sklearn.model_selection import GridSearchCV

In [ ]:
clf=GridSearchCV(SVC(gamma="auto"),{
    "C":[1,10,20,30],
    "kernel":["rbf","linear","poly",]
}, cv=5)
clf.fit(x,y)
clf.cv_results_  